name: pokemon_dependencies
description: Dependencies from project
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.1.2
  either_dart: ^0.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.6.0
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
