include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    prefer_single_quotes: true
    empty_statements: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    unnecessary_statements: true
    always_put_required_named_parameters_first: true
    always_declare_return_types: true
    lines_longer_than_80_chars: true
    null_check_on_nullable_type_parameter: true
    prefer_const_constructors: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    unnecessary_parenthesis: true
    unnecessary_overrides: true